### ISSUE TITLE
求作者联系方式

### ISSUE THREAD

**Issue by dly9685** [cooljacket/Dormitory-distribution#1]
因为我不会主学java，不会c++，但是我需要用到这个项目，求帮助，有偿

**Comment by cooljacket** [comment]
这种算法都过时好多年了，建议你用大模型 AI 工具来根据你的需求来写代码（比如通义千问、gpt3.5/4、claude之类的）。

**Comment by dly9685** [comment]
但是我们学校的要求就是要用贪心算法来完成，不会，请帮忙，谢谢了

**Comment by cooljacket** [comment]
贪心算法不就是每次都选择当前最好的即可吗？你如果真的理解了这一点，闭着眼都能写出代码来。
先考虑清楚：对于你要解决的问题来说，每次如何选出最好的，怎么定义“最好的”？
这个搞清楚之后，随便 for 几遍就可以了
